services:
  front-end:
    container_name: front-end
    build: .
    image: front-end
    networks:
      - betting-house-network
    ports:
      - 80:80
  
networks:
  my-network:
    name: betting-house-network
    external: true