services:
  front-end:
    container_name: front-end
    build: .
    image: front-end
    networks:
      - my-networks
    ports:
      - 80:80
  
networks:
  my-networks:
    name: my-networks
    external: true